version: "3"

services:
  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
    command: ["sh", "-c", "npm run start"]
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data: